#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nbval
Version  : 0.9.3
Release  : 1
URL      : https://files.pythonhosted.org/packages/ac/d6/57e2ad879a8277d317a0086e432abb11eecdd75ab3b40df12f08c3c30083/nbval-0.9.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/ac/d6/57e2ad879a8277d317a0086e432abb11eecdd75ab3b40df12f08c3c30083/nbval-0.9.3.tar.gz
Summary  : A py.test plugin to validate Jupyter notebooks
Group    : Development/Tools
License  : BSD-3-Clause
Requires: nbval-license = %{version}-%{release}
Requires: nbval-python = %{version}-%{release}
Requires: nbval-python3 = %{version}-%{release}
Requires: coverage
Requires: ipykernel
Requires: jupyter_client
Requires: nbformat
Requires: pytest
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : coverage
BuildRequires : ipykernel
BuildRequires : jupyter_client
BuildRequires : nbformat
BuildRequires : pytest
BuildRequires : six

%description
# Py.test plugin for validating Jupyter notebooks
[![Build Status](https://travis-ci.org/computationalmodelling/nbval.svg)](https://travis-ci.org/computationalmodelling/nbval)
[![PyPI Version](https://badge.fury.io/py/nbval.svg)](https://pypi.python.org/pypi/nbval)
[![Documentation Status](https://readthedocs.org/projects/nbval/badge/)](https://nbval.readthedocs.io/)

%package license
Summary: license components for the nbval package.
Group: Default

%description license
license components for the nbval package.


%package python
Summary: python components for the nbval package.
Group: Default
Requires: nbval-python3 = %{version}-%{release}

%description python
python components for the nbval package.


%package python3
Summary: python3 components for the nbval package.
Group: Default
Requires: python3-core

%description python3
python3 components for the nbval package.


%prep
%setup -q -n nbval-0.9.3
cd %{_builddir}/nbval-0.9.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1576268847
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/nbval
cp %{_builddir}/nbval-0.9.3/LICENSE %{buildroot}/usr/share/package-licenses/nbval/af20abb8f5fe7330fa3538addcc2ad10676b85f8
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/nbval/af20abb8f5fe7330fa3538addcc2ad10676b85f8

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
